name: Build and Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate image tag
        id: tag
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          SHORT_SHA=${GITHUB_SHA:0:7}
          echo "IMAGE_TAG=${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_OUTPUT
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/stepture-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/stepture-frontend:${{ steps.tag.outputs.IMAGE_TAG }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Azure VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USERNAME }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/stepture
            sed -i "s/FRONTEND_TAG=.*/FRONTEND_TAG=${{ steps.tag.outputs.IMAGE_TAG }}/" .env

            docker compose -f docker-compose.prod.yml pull frontend
            docker compose -f docker-compose.prod.yml up -d frontend nginx

            docker image prune -f

            docker images ${{ secrets.DOCKER_USERNAME }}/stepture-frontend --format "table {{.Tag}}" | tail -n +4 | head -n -3 | xargs -I {} docker rmi ${{ secrets.DOCKER_USERNAME }}/stepture-frontend:{} || true

            docker compose -f docker-compose.prod.yml ps
